grpc:
  enabled: true
  port: 10902
uiapi-properties:
  netty:
    http-block-max-byte: 65535
    ssl: false
    port: 10901
  security:
    auth:
    expire-minutes: 30
  window-size: 100
  shrink-threshold: 100
  subscribe:
    log: true
    log-sampling-second: 10
logging:
  path: log
  level:
    root: info
    subscribe: info
spring:
  application:
    name: uiapi
server:
  address: 127.0.0.1
  port: 8080
eureka:
  file-service-app-group-name: fileservice
  server:
    eviction-interval-timer-in-ms: 10000
  instance:
    non-secure-port: ${grpc.port}
    appname: uiapi
  client:
    service-url:
      defaultZone: http://${server.address}:${server.port}/eureka/
  dashboard:
    path: /eurekadashboard